---

- name: Deploy web app
  hosts: "web"
  become: yes
  gather_facts: True

  vars:
    - project_path: "/opt/{{ project_name }}"

  roles:
   - install_docker
   - copy_image
   - deploy_compose

