---
- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_only: yes

- name: Ensure a list of yum packages are installed
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
     - amazon-linux-extras

- name: Add extras repository
  shell: yum-config-manager --enable extras

- name: Install docker via amazon-linux-extras packages
  shell: "amazon-linux-extras install docker -y"

- name: Enable Docker CE service at startup
  service:
    name: docker
    state: started
    enabled: yes

- name: Install docker-compose
  shell: "sudo curl -L \"https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose"

- name: Make executable docker-compose
  shell: "sudo chmod +x /usr/local/bin/docker-compose"

- name: SLink docker-compose
  shell: "sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose || echo exists"

- name:
  template:
    src: docker-compose.yaml
    dest: "{{ project_path }}/docker-compose.yaml"
    mode: '0744'

- name:
  copy:
    src: docker-compose-start.sh
    dest: "{{ project_path }}/docker-compose-start.sh"
    mode: '0744'

- name: Stop previous compose
  shell: cmd="docker-compose down" chdir="{{ project_path }}"

- name: Create and start services
  shell: "sudo ./docker-compose-start.sh"
  args:
    executable: "/bin/bash"
    chdir: "{{ project_path }}"


